version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./caddy:/root/.caddy"
      - "./src:/srv"
    depends_on:
      - "db"
  db:
    image: "mariadb"
    volumes:
      - "./mariadb:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=my_db_name"
      - "MYSQL_USER=my_db_user"
      - "MYSQL_PASSWORD=my_db_user_passwd"
      - "MYSQL_ROOT_PASSWORD=my_db_root_passwd"
    expose:
      - "3306"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: always
    environment:
      - "PMA_HOST=db"
      - "MYSQL_USERNAME=root"
    ports:
      - "8080:80"
    links:
      - "db:db"
    depends_on:
      - "db"
